language:
  node_js:
    - "9.5.0"
install:
  - npm install
before_script:
  - npm install -g npm@'>=3'
script:
  - npm run test
  - npm run coverage
deploy:
  provider: npm
  email: hectotruj@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true